<?xml version="1.0"?>
<package format="2">
  <name>eggy_bringup</name>
  <version>0.1.0</version>
  <description>Launch and runtime configuration package for Eggy robot.</description>
  <maintainer email="eggy@example.com">eggy</maintainer>
  <license>MIT</license>
  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>eggy_base_driver</exec_depend>
  <exec_depend>eggy_robot_description</exec_depend>
  <export />
</package>
